#pragma once
#ifndef ADAPTIVEROUTEPLANNERTESTAPPLICATION_HPP

#include "AdaptiveRoutePlanner.hpp"
#include <iostream>
#include <time.h>

static const char * EnumStrings[]
{
	"XML_SUCCESS",
	"XML_NO_ATTRIBUTE",
	"XML_WRONG_ATTRIBUTE_TYPE",
	"XML_ERROR_FILE_NOT_FOUND",
	"XML_ERROR_FILE_COULD_NOT_BE_OPENED",
	"XML_ERROR_FILE_READ_ERROR",
	"XML_ERROR_ELEMENT_MISMATCH",
	"XML_ERROR_PARSING_ELEMENT",
	"XML_ERROR_PARSING_ATTRIBUTE",
	"XML_ERROR_IDENTIFYING_TAG",
	"XML_ERROR_PARSING_TEXT",
	"XML_ERROR_PARSING_CDATA",
	"XML_ERROR_PARSING_COMMENT",
	"XML_ERROR_PARSING_DECLARATION",
	"XML_ERROR_PARSING_UNKNOWN",
	"XML_ERROR_EMPTY_DOCUMENT",
	"XML_ERROR_MISMATCHED_ELEMENT",
	"XML_ERROR_PARSING",
	"XML_CAN_NOT_CONVERT_TEXT",
	"XML_NO_TEXT_NODE"
};

#endif // !ADAPTIVEROUTEPLANNERTESTAPPLICATION_HPP
