#pragma once
#ifndef ADAPTIVEROUTEPLANNERCONSTANTS_HPP

#define OSM_XML_ELEMENT_OSM "osm"
#define OSM_XML_ELEMENT_NODE "node"
#define OSM_XML_ELEMENT_TAG "tag"
#define OSM_XML_ELEMENT_WAY "way"
#define OSM_XML_ATTRIBUTE_NODE_ID "id"

#endif // !ADAPTIVEROUTEPLANNERCONSTANTS_HPP
