#pragma once
#ifndef ADAPTIVEROUTEPLANNERCONSTANTS_HPP

#include <map>

#define OSM_XML_ELEMENT_OSM "osm"
#define OSM_XML_ELEMENT_NODE "node"
#define OSM_XML_ELEMENT_TAG "tag"
#define OSM_XML_ELEMENT_WAY "way"
#define OSM_XML_ELEMENT_WAY_NODES "nd"
#define OSM_XML_ATTRIBUTE_WAY_NODES_ID "ref"
#define OSM_XML_ATTRIBUTE_NODE_ID "id"
#define OSM_XML_ATTRIBUTE_NODE_LON "lon"
#define OSM_XML_ATTRIBUTE_NODE_LAT "lat"
#define OSM_XML_ATTRIBUTE_TAG_KEY "k"
#define OSM_XML_ATTRIBUTE_TAG_VALUE "v"
#define OSM_XML_KEY_TAG_HIGHWAY "highway"
#define OSM_XML_KEY_TAG_MAXSPEED "maxspeed"
#define OSM_XML_KEY_TAG_ONEWAY "oneway"
#define OSM_XML_VALUE_ONEWAY_YES "yes"
#define OSM_XML_VALUE_HIGHWAY_MOTORWAY "motorway"
#define OSM_XML_VALUE_HIGHWAY_TRUNK "trunk"
#define OSM_XML_VALUE_HIGHWAY_PRIMARY "primary"
#define OSM_XML_VALUE_HIGHWAY_SECONDARY "secondary"
#define OSM_XML_VALUE_HIGHWAY_TERTIARY "tertiary"
#define OSM_XML_VALUE_HIGHWAY_UNCLASSIFIED "unclassified"
#define OSM_XML_VALUE_HIGHWAY_RESIDENTIAL "residential"
#define OSM_XML_VALUE_HIGHWAY_SERVICE "service"
#define OSM_XML_VALUE_HIGHWAY_MOTORWAY_LINK "motorway_link"
#define OSM_XML_VALUE_HIGHWAY_TRUNK_LINK "trunk_link"
#define OSM_XML_VALUE_HIGHWAY_PRIMARY_LINK "primary_link"
#define OSM_XML_VALUE_HIGHWAY_SECONDARY_LINK "secondary_link"
#define OSM_XML_VALUE_HIGHWAY_TERTIARY_LINK "tertiary_link"
#define OSM_XML_VALUE_HIGHWAY_LIVING_STREET "living_street"
#define DEFAULT_SPEED_LIMIT_130 130
#define DEFAULT_SPEED_LIMIT_100 100
#define DEFAULT_SPEED_LIMIT_50 50
#define DEFAULT_SPEED_LIMIT_10 10

static const std::unordered_map<const char*, int> DEFAULT_STREETS = {
	{ OSM_XML_VALUE_HIGHWAY_MOTORWAY,		DEFAULT_SPEED_LIMIT_130 },
	{ OSM_XML_VALUE_HIGHWAY_MOTORWAY_LINK,	DEFAULT_SPEED_LIMIT_130 },
	{ OSM_XML_VALUE_HIGHWAY_TRUNK,			DEFAULT_SPEED_LIMIT_100 },
	{ OSM_XML_VALUE_HIGHWAY_TRUNK_LINK,		DEFAULT_SPEED_LIMIT_100 },
	{ OSM_XML_VALUE_HIGHWAY_PRIMARY,		DEFAULT_SPEED_LIMIT_100 },
	{ OSM_XML_VALUE_HIGHWAY_PRIMARY_LINK,	DEFAULT_SPEED_LIMIT_100 },
	{ OSM_XML_VALUE_HIGHWAY_SECONDARY,		DEFAULT_SPEED_LIMIT_50 },
	{ OSM_XML_VALUE_HIGHWAY_SECONDARY_LINK,	DEFAULT_SPEED_LIMIT_50 },
	{ OSM_XML_VALUE_HIGHWAY_TERTIARY,		DEFAULT_SPEED_LIMIT_50 },
	{ OSM_XML_VALUE_HIGHWAY_TERTIARY_LINK,	DEFAULT_SPEED_LIMIT_50 },
	{ OSM_XML_VALUE_HIGHWAY_UNCLASSIFIED,	DEFAULT_SPEED_LIMIT_50 },
	{ OSM_XML_VALUE_HIGHWAY_RESIDENTIAL,	DEFAULT_SPEED_LIMIT_50 },
	{ OSM_XML_VALUE_HIGHWAY_SERVICE,		DEFAULT_SPEED_LIMIT_50 },
	{ OSM_XML_VALUE_HIGHWAY_LIVING_STREET,	DEFAULT_SPEED_LIMIT_10 }
};

#endif // !ADAPTIVEROUTEPLANNERCONSTANTS_HPP
